// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package event_data_store

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}
	customPreCompare(delta, a, b)

	if !reflect.DeepEqual(a.ko.Spec.AdvancedEventSelectors, b.ko.Spec.AdvancedEventSelectors) {
		delta.Add("Spec.AdvancedEventSelectors", a.ko.Spec.AdvancedEventSelectors, b.ko.Spec.AdvancedEventSelectors)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MultiRegionEnabled, b.ko.Spec.MultiRegionEnabled) {
		delta.Add("Spec.MultiRegionEnabled", a.ko.Spec.MultiRegionEnabled, b.ko.Spec.MultiRegionEnabled)
	} else if a.ko.Spec.MultiRegionEnabled != nil && b.ko.Spec.MultiRegionEnabled != nil {
		if *a.ko.Spec.MultiRegionEnabled != *b.ko.Spec.MultiRegionEnabled {
			delta.Add("Spec.MultiRegionEnabled", a.ko.Spec.MultiRegionEnabled, b.ko.Spec.MultiRegionEnabled)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.OrganizationEnabled, b.ko.Spec.OrganizationEnabled) {
		delta.Add("Spec.OrganizationEnabled", a.ko.Spec.OrganizationEnabled, b.ko.Spec.OrganizationEnabled)
	} else if a.ko.Spec.OrganizationEnabled != nil && b.ko.Spec.OrganizationEnabled != nil {
		if *a.ko.Spec.OrganizationEnabled != *b.ko.Spec.OrganizationEnabled {
			delta.Add("Spec.OrganizationEnabled", a.ko.Spec.OrganizationEnabled, b.ko.Spec.OrganizationEnabled)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RetentionPeriod, b.ko.Spec.RetentionPeriod) {
		delta.Add("Spec.RetentionPeriod", a.ko.Spec.RetentionPeriod, b.ko.Spec.RetentionPeriod)
	} else if a.ko.Spec.RetentionPeriod != nil && b.ko.Spec.RetentionPeriod != nil {
		if *a.ko.Spec.RetentionPeriod != *b.ko.Spec.RetentionPeriod {
			delta.Add("Spec.RetentionPeriod", a.ko.Spec.RetentionPeriod, b.ko.Spec.RetentionPeriod)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.TerminationProtectionEnabled, b.ko.Spec.TerminationProtectionEnabled) {
		delta.Add("Spec.TerminationProtectionEnabled", a.ko.Spec.TerminationProtectionEnabled, b.ko.Spec.TerminationProtectionEnabled)
	} else if a.ko.Spec.TerminationProtectionEnabled != nil && b.ko.Spec.TerminationProtectionEnabled != nil {
		if *a.ko.Spec.TerminationProtectionEnabled != *b.ko.Spec.TerminationProtectionEnabled {
			delta.Add("Spec.TerminationProtectionEnabled", a.ko.Spec.TerminationProtectionEnabled, b.ko.Spec.TerminationProtectionEnabled)
		}
	}

	return delta
}
