// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	"github.com/aws/aws-sdk-go/aws"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = ackv1alpha1.AWSAccountID("")
)

// Advanced event selectors let you create fine-grained selectors for CloudTrail
// management, data, and network activity events. They help you control costs
// by logging only those events that are important to you. For more information
// about configuring advanced event selectors, see the Logging data events (https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-data-events-with-cloudtrail.html),
// Logging network activity events (https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-network-events-with-cloudtrail.html),
// and Logging management events (https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-management-events-with-cloudtrail.html)
// topics in the CloudTrail User Guide.
//
// You cannot apply both event selectors and advanced event selectors to a trail.
//
// Supported CloudTrail event record fields for management events
//
//   - eventCategory (required)
//
//   - eventSource
//
//   - readOnly
//
// The following additional fields are available for event data stores:
//
//   - eventName
//
//   - eventType
//
//   - sessionCredentialFromConsole
//
//   - userIdentity.arn
//
// Supported CloudTrail event record fields for data events
//
//   - eventCategory (required)
//
//   - resources.type (required)
//
//   - readOnly
//
//   - eventName
//
//   - resources.ARN
//
// The following additional fields are available for event data stores:
//
//   - eventSource
//
//   - eventType
//
//   - sessionCredentialFromConsole
//
//   - userIdentity.arn
//
// # Supported CloudTrail event record fields for network activity events
//
// Network activity events is in preview release for CloudTrail and is subject
// to change.
//
//   - eventCategory (required)
//
//   - eventSource (required)
//
//   - eventName
//
//   - errorCode - The only valid value for errorCode is VpceAccessDenied.
//
//   - vpcEndpointId
//
// For event data stores for CloudTrail Insights events, Config configuration
// items, Audit Manager evidence, or events outside of Amazon Web Services,
// the only supported field is eventCategory.
type AdvancedEventSelector struct {
	FieldSelectors []*AdvancedFieldSelector `json:"fieldSelectors,omitempty"`
	Name           *string                  `json:"name,omitempty"`
}

// A single selector statement in an advanced event selector.
type AdvancedFieldSelector struct {
	EndsWith      []*string `json:"endsWith,omitempty"`
	Equals        []*string `json:"equals,omitempty"`
	Field         *string   `json:"field,omitempty"`
	NotEndsWith   []*string `json:"notEndsWith,omitempty"`
	NotEquals     []*string `json:"notEquals,omitempty"`
	NotStartsWith []*string `json:"notStartsWith,omitempty"`
	StartsWith    []*string `json:"startsWith,omitempty"`
}

// You can configure the DataResource in an EventSelector to log data events
// for the following three resource types:
//
//   - AWS::DynamoDB::Table
//
//   - AWS::Lambda::Function
//
//   - AWS::S3::Object
//
// To log data events for all other resource types including objects stored
// in directory buckets (https://docs.aws.amazon.com/AmazonS3/latest/userguide/directory-buckets-overview.html),
// you must use AdvancedEventSelectors (https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_AdvancedEventSelector.html).
// You must also use AdvancedEventSelectors if you want to filter on the eventName
// field.
//
// Configure the DataResource to specify the resource type and resource ARNs
// for which you want to log data events.
//
// The total number of allowed data resources is 250. This number can be distributed
// between 1 and 5 event selectors, but the total cannot exceed 250 across all
// selectors for the trail.
//
// The following example demonstrates how logging works when you configure logging
// of all data events for a general purpose bucket named amzn-s3-demo-bucket1.
// In this example, the CloudTrail user specified an empty prefix, and the option
// to log both Read and Write data events.
//
// A user uploads an image file to amzn-s3-demo-bucket1.
//
// The PutObject API operation is an Amazon S3 object-level API. It is recorded
// as a data event in CloudTrail. Because the CloudTrail user specified an S3
// bucket with an empty prefix, events that occur on any object in that bucket
// are logged. The trail processes and logs the event.
//
// A user uploads an object to an Amazon S3 bucket named arn:aws:s3:::amzn-s3-demo-bucket1.
//
// The PutObject API operation occurred for an object in an S3 bucket that the
// CloudTrail user didn't specify for the trail. The trail doesn’t log the
// event.
//
// The following example demonstrates how logging works when you configure logging
// of Lambda data events for a Lambda function named MyLambdaFunction, but not
// for all Lambda functions.
//
// A user runs a script that includes a call to the MyLambdaFunction function
// and the MyOtherLambdaFunction function.
//
// The Invoke API operation on MyLambdaFunction is an Lambda API. It is recorded
// as a data event in CloudTrail. Because the CloudTrail user specified logging
// data events for MyLambdaFunction, any invocations of that function are logged.
// The trail processes and logs the event.
//
// The Invoke API operation on MyOtherLambdaFunction is an Lambda API. Because
// the CloudTrail user did not specify logging data events for all Lambda functions,
// the Invoke operation for MyOtherLambdaFunction does not match the function
// specified for the trail. The trail doesn’t log the event.
type DataResource struct {
	Type *string `json:"type_,omitempty"`
}

// Contains information about an event that was returned by a lookup request.
// The result includes a representation of a CloudTrail event.
type Event struct {
	AccessKeyID     *string      `json:"accessKeyID,omitempty"`
	CloudTrailEvent *string      `json:"cloudTrailEvent,omitempty"`
	EventID         *string      `json:"eventID,omitempty"`
	EventName       *string      `json:"eventName,omitempty"`
	EventSource     *string      `json:"eventSource,omitempty"`
	EventTime       *metav1.Time `json:"eventTime,omitempty"`
	ReadOnly        *string      `json:"readOnly,omitempty"`
	Username        *string      `json:"username,omitempty"`
}

// A storage lake of event data against which you can run complex SQL-based
// queries. An event data store can include events that you have logged on your
// account. To select events for an event data store, use advanced event selectors
// (https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-lake-concepts.html#adv-event-selectors).
type EventDataStore_SDK struct {
	AdvancedEventSelectors       []*AdvancedEventSelector `json:"advancedEventSelectors,omitempty"`
	CreatedTimestamp             *metav1.Time             `json:"createdTimestamp,omitempty"`
	EventDataStoreARN            *string                  `json:"eventDataStoreARN,omitempty"`
	MultiRegionEnabled           *bool                    `json:"multiRegionEnabled,omitempty"`
	Name                         *string                  `json:"name,omitempty"`
	OrganizationEnabled          *bool                    `json:"organizationEnabled,omitempty"`
	RetentionPeriod              *int64                   `json:"retentionPeriod,omitempty"`
	Status                       *string                  `json:"status,omitempty"`
	TerminationProtectionEnabled *bool                    `json:"terminationProtectionEnabled,omitempty"`
	UpdatedTimestamp             *metav1.Time             `json:"updatedTimestamp,omitempty"`
}

// Use event selectors to further specify the management and data event settings
// for your trail. By default, trails created without specific event selectors
// will be configured to log all read and write management events, and no data
// events. When an event occurs in your account, CloudTrail evaluates the event
// selector for all trails. For each trail, if the event matches any event selector,
// the trail processes and logs the event. If the event doesn't match any event
// selector, the trail doesn't log the event.
//
// You can configure up to five event selectors for a trail.
//
// You cannot apply both event selectors and advanced event selectors to a trail.
type EventSelector struct {
	IncludeManagementEvents *bool `json:"includeManagementEvents,omitempty"`
}

// Provides information about an import failure.
type ImportFailureListItem struct {
	ErrorMessage    *string      `json:"errorMessage,omitempty"`
	ErrorType       *string      `json:"errorType,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
	Location        *string      `json:"location,omitempty"`
}

// Contains information about an import that was returned by a lookup request.
type ImportsListItem struct {
	CreatedTimestamp *metav1.Time `json:"createdTimestamp,omitempty"`
	UpdatedTimestamp *metav1.Time `json:"updatedTimestamp,omitempty"`
}

// A table showing information about the most recent successful and failed attempts
// to ingest events.
type IngestionStatus struct {
	LatestIngestionAttemptTime *metav1.Time `json:"latestIngestionAttemptTime,omitempty"`
	LatestIngestionSuccessTime *metav1.Time `json:"latestIngestionSuccessTime,omitempty"`
}

// Contains information about a partition key for an event data store.
type PartitionKey struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type_,omitempty"`
}

// Contains information about a returned public key.
type PublicKey struct {
	Fingerprint       *string      `json:"fingerprint,omitempty"`
	ValidityEndTime   *metav1.Time `json:"validityEndTime,omitempty"`
	ValidityStartTime *metav1.Time `json:"validityStartTime,omitempty"`
}

// A SQL string of criteria about events that you want to collect in an event
// data store.
type Query struct {
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
}

// Gets metadata about a query, including the number of events that were matched,
// the total number of events scanned, the query run time in milliseconds, and
// the query's creation time.
type QueryStatisticsForDescribeQuery struct {
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
}

// Specifies the type and name of a resource referenced by an event.
type Resource struct {
	ResourceName *string `json:"resourceName,omitempty"`
	ResourceType *string `json:"resourceType,omitempty"`
}

// A resource tag.
type ResourceTag struct {
	ResourceID *string `json:"resourceID,omitempty"`
	// A list of tags.
	TagsList []*Tag `json:"tagsList,omitempty"`
}

// The settings for the source S3 bucket.
type S3ImportSource struct {
	S3BucketAccessRoleARN *string `json:"s3BucketAccessRoleARN,omitempty"`
	S3BucketRegion        *string `json:"s3BucketRegion,omitempty"`
	S3LocationURI         *string `json:"s3LocationURI,omitempty"`
}

// Contains configuration information about the channel.
type SourceConfig struct {
	AdvancedEventSelectors []*AdvancedEventSelector `json:"advancedEventSelectors,omitempty"`
	ApplyToAllRegions      *bool                    `json:"applyToAllRegions,omitempty"`
}

// A custom key-value pair associated with a resource such as a CloudTrail trail,
// event data store, dashboard, or channel.
type Tag struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// Information about a CloudTrail trail, including the trail's name, home Region,
// and Amazon Resource Name (ARN).
type TrailInfo struct {
	HomeRegion *string `json:"homeRegion,omitempty"`
	Name       *string `json:"name,omitempty"`
	TrailARN   *string `json:"trailARN,omitempty"`
}

// The settings for a trail.
type Trail_SDK struct {
	CloudWatchLogsLogGroupARN  *string `json:"cloudWatchLogsLogGroupARN,omitempty"`
	CloudWatchLogsRoleARN      *string `json:"cloudWatchLogsRoleARN,omitempty"`
	HasCustomEventSelectors    *bool   `json:"hasCustomEventSelectors,omitempty"`
	HasInsightSelectors        *bool   `json:"hasInsightSelectors,omitempty"`
	HomeRegion                 *string `json:"homeRegion,omitempty"`
	IncludeGlobalServiceEvents *bool   `json:"includeGlobalServiceEvents,omitempty"`
	IsMultiRegionTrail         *bool   `json:"isMultiRegionTrail,omitempty"`
	IsOrganizationTrail        *bool   `json:"isOrganizationTrail,omitempty"`
	KMSKeyID                   *string `json:"kmsKeyID,omitempty"`
	LogFileValidationEnabled   *bool   `json:"logFileValidationEnabled,omitempty"`
	Name                       *string `json:"name,omitempty"`
	S3BucketName               *string `json:"s3BucketName,omitempty"`
	S3KeyPrefix                *string `json:"s3KeyPrefix,omitempty"`
	SNSTopicARN                *string `json:"snsTopicARN,omitempty"`
	SNSTopicName               *string `json:"snsTopicName,omitempty"`
	TrailARN                   *string `json:"trailARN,omitempty"`
}
